apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-ansible-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: etcd-ansible-operator
  template:
    metadata:
      labels:
        name: etcd-ansible-operator
    spec:
      serviceAccountName: etcd-ansible-operator
      containers:
        - name: etcd-ansible-operator
          image: docker.io/alaypatel07/etcd-ansible-operator:v0.5.0
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "etcd-ansible-operator"
